### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by luqmaan**
:kiss:

### CODE REVIEW

**Comment by fremn** [comment]
looks like all this does is introduce a syntax error

**Comment by luqmaan** [comment]
:smiling_imp:

**Comment by johntyree** [comment]
:+1:

**Comment by luqmaan** [comment]
LGTM

**Comment by scascketta** [comment]
Seems legit. :+1:

**Comment by croath** [comment]
:+1:

**Comment by benweatherman** [comment]
Thank you for your commitment to open source

**Comment by luqmaan** [comment]
It is my honor and privilege.

**Pull request merged**
