### PR TITLE
Add some placholder directories

### PR DESCRIPTION
**Pull request by paf31**
This project will need some files to put Javascript code in.

### CODE REVIEW

**Comment by heyday665** [comment]
Why would you do this!?!

**Comment by paf31** [comment]
@heyday665 It needed more directories.

**Comment by KrisSiegel** [comment]
"Sorry, we could not display the entire diff because too many files (637) changed."

This may qualify for rejection under the "don't be a dick" rule :)

**Comment by paf31** [comment]
:sob:

**Pull request closed without merging**
